# Generated by Django 5.2.13 on 2026-04-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Эон', max_length=100)),
                ('credits', models.IntegerField(default=300)),
                ('stress', models.IntegerField(default=25)),
                ('fatigue', models.IntegerField(default=20)),
            ],
        ),
    ]
