# Generated by Django 5.2.13 on 2026-05-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='clearance_index',
            field=models.IntegerField(default=27),
        ),
    ]
