# Generated by Django 5.2.13 on 2026-05-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_character_clearance_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DronePuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grid_width', models.IntegerField(default=3)),
                ('grid_height', models.IntegerField(default=3)),
                ('start_x', models.IntegerField(default=0)),
                ('start_y', models.IntegerField(default=0)),
                ('finish_x', models.IntegerField(default=2)),
                ('finish_y', models.IntegerField(default=2)),
                ('broken_cells', models.TextField(default='[]')),
                ('is_solved', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
    ]
