# Generated by Django 5.2.13 on 2026-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronepuzzle',
            name='battery',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='dronepuzzle',
            name='hint_code',
            field=models.TextField(blank=True, help_text='Пример кода-подсказки'),
        ),
        migrations.AddField(
            model_name='dronepuzzle',
            name='items',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='dronepuzzle',
            name='max_steps',
            field=models.IntegerField(default=20),
        ),
    ]
